import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { basename, dirname } from "node:path";
import { fileURLToPath } from "node:url";

import { runtimeDeployPlugin } from "../deploy-runtime.mjs";

const sourceFolder = basename(dirname(fileURLToPath(import.meta.url)));
const production = process.argv[2] === "production";
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
Source: https://github.com/ZachTish/tps-linter
*/
`;

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
  plugins: [runtimeDeployPlugin(sourceFolder)],
});

if (production) {
  await context.rebuild();
  process.exit(0);
}

await context.watch();
